import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import bookList from '../utiles/data';
import styles from '@/styles/Home.module.scss';
import Layout from '@/components/Layout';
import { Store } from '@/contexts/Store';
import Book from '@/components/Book';
import { useMemo } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const {
    filterList,
    noRes,
    searchVal,
    sortValue,
    setSortValue,
    sortList,
    setSortList,
  } = Store();

  useMemo(() => {
    if (sortValue === 'title') {
      setSortList(
        bookList.sort((a, b) => {
          if (a.title < b.title) {
            return -1;
          }
          if (a.title > b.title) {
            return 1;
          }
        })
      );
    }
    if (sortValue === 'author') {
      setSortList(
        bookList.sort((a, b) => {
          if (a.author < b.author) {
            return -1;
          }
          if (a.author > b.author) {
            return 1;
          }
        })
      );
    }
    if (sortValue === 'genre') {
      setSortList(
        bookList.sort((a, b) => {
          if (a.genre < b.genre) {
            return -1;
          }
          if (a.genre > b.genre) {
            return 1;
          }
        })
      );
    }
  }, [sortValue]);
  return (
    <Layout>
      <Head>
        <title> Search Bookes </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className={styles.sort_data}>
          <select
          className={styles.select}
            onChange={e => {
              setSortValue(e.target.value);
            }}
          >
            <option value={'title'}> by title</option>
            <option value={'author'}> by author</option>
            <option value={'genre'}> by genre</option>
          </select>
        </div>
        <div className={styles.book_shif}>
          {noRes === true && searchVal !== '' ? (
            <h1>There is no result for your search</h1>
          ) : filterList.length > 0 ? (
            filterList.map((x, index) => <Book key={index} data={x} />)
          ) : (
            sortList.map((x, index) => <Book key={index} data={x} />)
          )}
        </div>
      </main>
    </Layout>
  );
}
